name = "mateusap1/comp"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'mateusap1/comp'"

[repository]
user = "mateusap1"
project = "comp"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.8.0"
source = "github"
